using System;
using System.Collections.Generic;
using System.Text;

namespace ALISS.Process.Batch.Model
{
    public class TRProcessDataResult
    {
        public int pdr_id { get; set; }
        public string pdr_pcr_code { get; set; }
        public string pdr_arh_code { get; set; }
        public string pdr_prv_code { get; set; }
        public string pdr_hos_code { get; set; }
        public string pdr_lab_code { get; set; }
        public string pdr_specimen { get; set; }
        public string pdr_pathogen { get; set; }
        public string pdr_row_idx { get; set; }
        public string pdr_organisms { get; set; }
        public string pdr_isolates { get; set; }
        public string pdr_drug_code { get; set; }
        public string pdr_drug_name { get; set; }
        public string pdr_class { get; set; }
        public string pdr_subclass { get; set; }
        public string pdr_drug_code1 { get; set; }
        public string pdr_methods { get; set; }
        public string pdr_bp_type { get; set; }
        public string pdr_site_inf { get; set; }
        public string pdr_host { get; set; }
        public string pdr_breakpoint { get; set; }
        public string pdr_num_tested { get; set; }
        public string pdr_perc_res { get; set; }
        public string pdr_perc_resx { get; set; }
        public string pdr_perc_int { get; set; }
        public string pdr_perc_susc { get; set; }
        public string pdr_perc_suscx { get; set; }
        public string pdr_perc_unk { get; set; }
        public string pdr_res_ci { get; set; }
        public string pdr_mic50 { get; set; }
        public string pdr_mic90 { get; set; }
        public string pdr_geom_mean { get; set; }
        public string pdr_mic_range { get; set; }
        public string pdr_num_quant { get; set; }
        public string pdr_zone_6 { get; set; }
        public string pdr_zone_7 { get; set; }
        public string pdr_zone_8 { get; set; }
        public string pdr_zone_9 { get; set; }
        public string pdr_zone_10 { get; set; }
        public string pdr_zone_11 { get; set; }
        public string pdr_zone_12 { get; set; }
        public string pdr_zone_13 { get; set; }
        public string pdr_zone_14 { get; set; }
        public string pdr_zone_15 { get; set; }
        public string pdr_zone_16 { get; set; }
        public string pdr_zone_17 { get; set; }
        public string pdr_zone_18 { get; set; }
        public string pdr_zone_19 { get; set; }
        public string pdr_zone_20 { get; set; }
        public string pdr_zone_21 { get; set; }
        public string pdr_zone_22 { get; set; }
        public string pdr_zone_23 { get; set; }
        public string pdr_zone_24 { get; set; }
        public string pdr_zone_25 { get; set; }
        public string pdr_zone_26 { get; set; }
        public string pdr_zone_27 { get; set; }
        public string pdr_zone_28 { get; set; }
        public string pdr_zone_29 { get; set; }
        public string pdr_zone_30 { get; set; }
        public string pdr_zone_31 { get; set; }
        public string pdr_zone_32 { get; set; }
        public string pdr_zone_33 { get; set; }
        public string pdr_zone_34 { get; set; }
        public string pdr_zone_35 { get; set; }
        public string pdr_zone__35 { get; set; }
        public string pdr_mic_L_001 { get; set; }
        public string pdr_mic__0015 { get; set; }
        public string pdr_mic__002 { get; set; }
        public string pdr_mic__003 { get; set; }
        public string pdr_mic__004 { get; set; }
        public string pdr_mic__006 { get; set; }
        public string pdr_mic__008 { get; set; }
        public string pdr_mic__012 { get; set; }
        public string pdr_mic__016 { get; set; }
        public string pdr_mic__023 { get; set; }
        public string pdr_mic__032 { get; set; }
        public string pdr_mic__047 { get; set; }
        public string pdr_mic__064 { get; set; }
        public string pdr_mic__094 { get; set; }
        public string pdr_mic__125 { get; set; }
        public string pdr_mic__19 { get; set; }
        public string pdr_mic__25 { get; set; }
        public string pdr_mic__38 { get; set; }
        public string pdr_mic__5 { get; set; }
        public string pdr_mic__75 { get; set; }
        public string pdr_mic_1 { get; set; }
        public string pdr_mic_1_5 { get; set; }
        public string pdr_mic_2 { get; set; }
        public string pdr_mic_3 { get; set; }
        public string pdr_mic_4 { get; set; }
        public string pdr_mic_6 { get; set; }
        public string pdr_mic_8 { get; set; }
        public string pdr_mic_12 { get; set; }
        public string pdr_mic_16 { get; set; }
        public string pdr_mic_24 { get; set; }
        public string pdr_mic_32 { get; set; }
        public string pdr_mic_48 { get; set; }
        public string pdr_mic_64 { get; set; }
        public string pdr_mic_96 { get; set; }
        public string pdr_mic_128 { get; set; }
        public string pdr_mic_192 { get; set; }
        public string pdr_mic_256 { get; set; }
        public string pdr_mic_384 { get; set; }
        public string pdr_mic_g256 { get; set; }
        public string pdr_createuser { get; set; }
        public DateTime? pdr_createdate { get; set; }
        public string pdr_updateuser { get; set; }
        public DateTime? pdr_updatedate { get; set; }
    }
}
