using System;
using System.Collections.Generic;
using System.Text;

namespace ALISS.LabFileUpload.Batch.Models
{
    public class TRSTGLabNarstData_DISK
    {
        public int lnd_id { get; set; }
        public Guid? lnd_lfu_id { get; set; }
        public string lnd_lfu_Program { get; set; }
        public string lnd_lfu_FileType { get; set; }
        public string lnd_lfu_FileTypeLabel { get; set; }
        public string lnd_arh_code { get; set; }
        public string lnd_prv_code { get; set; }
        public string lnd_hos_code { get; set; }
        public string lnd_lab { get; set; }
        public string lnd_labno { get; set; }
        public string lnd_cdate { get; set; }
        public string lnd_csource { get; set; }
        public string lnd_corganism { get; set; }
        public string lnd_date_birth_str { get; set; }
        public string lnd_organism_original_value { get; set; }
        public string lnd_specimen_original_value { get; set; }
        public string lnd_wardtype_original_value { get; set; }
        public string lnd_status { get; set; }
        public int lnd_sequence { get; set; }
        public string lnd_his_refno { get; set; }
        public string lnd_his_hnno { get; set; }
        public string lnd_createuser { get; set; }
        public DateTime? lnd_createdate { get; set; }
        public string lnd_updateuser { get; set; }
        public DateTime? lnd_updatedate { get; set; }
        public string COUNTRY_A { get; set; }
        public string LABORATORY { get; set; }
        public string ORIGIN { get; set; }
        public string PATIENT_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string SEX { get; set; }
        public DateTime? DATE_BIRTH { get; set; }
        public string AGE { get; set; }
        public string PAT_TYPE { get; set; }
        public string WARD { get; set; }
        public string INSTITUT { get; set; }
        public string DEPARTMENT { get; set; }
        public string WARD_TYPE { get; set; }
        public string SPEC_NUM { get; set; }
        public DateTime? SPEC_DATE { get; set; }
        public string SPEC_TYPE { get; set; }
        public string SPEC_CODE { get; set; }
        public string SPEC_REAS { get; set; }
        public string ISOL_NUM { get; set; }
        public string ORGANISM { get; set; }
        public string ORG_TYPE { get; set; }
        public string SEROTYPE { get; set; }
        public string BETA_LACT { get; set; }
        public string ESBL { get; set; }
        public string CARBAPENEM { get; set; }
        public string MRSA_SCRN { get; set; }
        public string INDUC_CLI { get; set; }
        public DateTime? DATE_DATA { get; set; }
        public string COMMENT { get; set; }
        public string NOSOCOMIAL { get; set; }
        public DateTime? DATE_ADMIS { get; set; }
        public string AMK_ND30 { get; set; }
        public string AMC_ND20 { get; set; }
        public string AMP_ND10 { get; set; }
        public string SAM_ND10 { get; set; }
        public string AZM_ND15 { get; set; }
        public string CZO_ND30 { get; set; }
        public string FEP_ND30 { get; set; }
        public string CFM_ND5 { get; set; }
        public string CSL_ND30 { get; set; }
        public string CTX_ND30 { get; set; }
        public string FOX_ND30 { get; set; }
        public string CAZ_ND30 { get; set; }
        public string CZX_ND30 { get; set; }
        public string CRO_ND30 { get; set; }
        public string CXA_ND30 { get; set; }
        public string CXM_ND30 { get; set; }
        public string CHL_ND30 { get; set; }
        public string CIP_ND5 { get; set; }
        public string CLI_ND2 { get; set; }
        public string COL_ND10 { get; set; }
        public string DAP_ND30 { get; set; }
        public string DOR_ND10 { get; set; }
        public string ETP_ND10 { get; set; }
        public string ERY_ND15 { get; set; }
        public string FOS_ND200 { get; set; }
        public string FUS_ND10 { get; set; }
        public string GEN_ND10 { get; set; }
        public string GEH_ND120 { get; set; }
        public string IPM_ND10 { get; set; }
        public string LVX_ND5 { get; set; }
        public string MEM_ND10 { get; set; }
        public string NAL_ND30 { get; set; }
        public string NET_ND30 { get; set; }
        public string NIT_ND300 { get; set; }
        public string NOR_ND10 { get; set; }
        public string OFX_ND5 { get; set; }
        public string OXA_ND1 { get; set; }
        public string PEN_ND10 { get; set; }
        public string PIP_ND100 { get; set; }
        public string TZP_ND100 { get; set; }
        public string POL_ND300 { get; set; }
        public string STH_ND300 { get; set; }
        public string STR_ND10 { get; set; }
        public string TEC_ND30 { get; set; }
        public string TCY_ND30 { get; set; }
        public string SXT_ND1_2 { get; set; }
        public string VAN_ND30 { get; set; }     
        public string SPT_ND100 { get; set; }       
        public string AMC_ND30 { get; set; }
        public string AMX_ND10 { get; set; }
        public string AMX_ND30 { get; set; }
        public string ANI_ND { get; set; }
        public string ATM_ND30 { get; set; }   
        public string AXS_ND { get; set; }
        public string BIA_ND { get; set; }     
        public string CAP_ND { get; set; }
        public string CAS_ND5 { get; set; }     
        public string CCV_ND30 { get; set; }      
        public string CDR_ND5 { get; set; }       
        public string CEP_ND30 { get; set; }       
        public string CFP_ND75 { get; set; }    
        public string CLO_ND5 { get; set; }
        public string CLR_ND15 { get; set; }
        public string CLR_ND5 { get; set; }     
        public string CNX_ND { get; set; }   
        public string CPD_ND10 { get; set; }
        public string CPO_ND30 { get; set; }      
        public string CPT_ND30 { get; set; }     
        public string CTC_ND30 { get; set; }
        public string CYC_ND { get; set; }      
        public string CZT_ND30 { get; set; }     
        public string DOX_ND30 { get; set; }      
        public string ETH_ND { get; set; }
        public string ETI_ND { get; set; }
        public string FLU_ND25 { get; set; }     
        public string FOS_ND50 { get; set; }      
        public string INH_ND { get; set; }       
        public string KAN_ND30 { get; set; }      
        public string LVX_ND1 { get; set; }
        public string MET_ND5 { get; set; }     
        public string MFX_ND5 { get; set; }     
        public string MIF_ND10 { get; set; } 
        public string NEO_ND30 { get; set; }
        public string NOV_ND100 { get; set; }
        public string NOV_ND5 { get; set; }   
        public string OPT_ND5 { get; set; }
        public string PAS_ND { get; set; }
        public string PEF_ND5 { get; set; }
        public string PIS_ND30 { get; set; }
        public string POP_ND300 { get; set; }
        public string POS_ND5 { get; set; }       
        public string RIF_ND5 { get; set; }       
        public string SIT_ND { get; set; }       
        public string TCC_ND75 { get; set; }     
        public string TGC_ND15 { get; set; }      
        public string TOB_ND10 { get; set; }     
        public string VOR_ND1 { get; set; }
      
    }
}
