using System;
using System.Collections.Generic;
using System.Text;

namespace ALISS.LabFileUpload.Batch.Models
{
    public class TRSTGLabNarstData_MIC
    {
        public int lnm_id { get; set; }
        public Guid? lnm_lfu_id { get; set; }
        public string lnm_lfu_Program { get; set; }
        public string lnm_lfu_FileType { get; set; }
        public string lnm_lfu_FileTypeLabel { get; set; }
        public string lnm_arh_code { get; set; }
        public string lnm_prv_code { get; set; }
        public string lnm_hos_code { get; set; }
        public string lnm_lab { get; set; }
        public string lnm_labno { get; set; }
        public string lnm_cdate { get; set; }
        public string lnm_csource { get; set; }
        public string lnm_corganism { get; set; }
        public string lnm_date_birth_str { get; set; }
        public string lnm_organism_original_value { get; set; }
        public string lnm_specimen_original_value { get; set; }
        public string lnm_wardtype_original_value { get; set; }
        public string lnm_status { get; set; }
        public int lnm_sequence { get; set; }
        public string lnm_his_refno { get; set; }
        public string lnm_his_hnno { get; set; }
        public string lnm_createuser { get; set; }
        public DateTime? lnm_createdate { get; set; }
        public string lnm_updateuser { get; set; }
        public DateTime? lnm_updatedate { get; set; }
        public string COUNTRY_A { get; set; }
        public string LABORATORY { get; set; }
        public string ORIGIN { get; set; }
        public string PATIENT_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string SEX { get; set; }
        public DateTime? DATE_BIRTH { get; set; }
        public string AGE { get; set; }
        public string PAT_TYPE { get; set; }
        public string WARD { get; set; }
        public string INSTITUT { get; set; }
        public string DEPARTMENT { get; set; }
        public string WARD_TYPE { get; set; }
        public string SPEC_NUM { get; set; }
        public DateTime? SPEC_DATE { get; set; }
        public string SPEC_TYPE { get; set; }
        public string SPEC_CODE { get; set; }
        public string SPEC_REAS { get; set; }
        public string ISOL_NUM { get; set; }
        public string ORGANISM { get; set; }
        public string ORG_TYPE { get; set; }
        public string SEROTYPE { get; set; }
        public string BETA_LACT { get; set; }
        public string ESBL { get; set; }
        public string CARBAPENEM { get; set; }
        public string MRSA_SCRN { get; set; }
        public string INDUC_CLI { get; set; }
        public DateTime? DATE_DATA { get; set; }
        public string COMMENT { get; set; }
        public string NOSOCOMIAL { get; set; }
        public DateTime? DATE_ADMIS { get; set; }         
        public string CTX_NM { get; set; }     
        public string CAZ_NM { get; set; }   
        public string CZX_NM { get; set; }   
        public string CRO_NM { get; set; }        
        public string CHL_NM { get; set; }     
        public string CIP_NM { get; set; }
        public string CLI_NM { get; set; }      
        public string COL_NM { get; set; }    
        public string DAP_NM { get; set; }     
        public string ETP_NM { get; set; }    
        public string ERY_NM { get; set; }     
        public string IPM_NM { get; set; }       
        public string MEM_NM { get; set; }       
        public string NET_NM { get; set; }       
        public string PEN_NM { get; set; }       
        public string VAN_NM { get; set; }            
        public string GEN_NM { get; set; }    
        public string TCY_NM { get; set; }      
        public string CXM_NM { get; set; }       
        public string AMP_NM { get; set; }       
        public string FEP_NM { get; set; }       
        public string LVX_NM { get; set; }       
        public string AMK_NM { get; set; }       
        public string TZP_NM { get; set; }      
        public string SAM_NM { get; set; }     
        public string CZO_NM { get; set; }      
        public string AZM_NM { get; set; }       
        public string CXA_NM { get; set; }        
        public string AMC_NM { get; set; }        
        public string CSL_NM { get; set; }        
        public string OXA_NM { get; set; }        
        public string FOX_NM { get; set; }       
        public string NOR_NM { get; set; }
        public string GEH_NM { get; set; }       
        public string TEC_NM { get; set; }        
        public string FOS_NM { get; set; }       
        public string NIT_NM { get; set; }       
        public string SXT_NM { get; set; }        
        public string DOR_NM { get; set; }   
        public string AMX_NM { get; set; }      
        public string ATM_NM { get; set; }     
        public string BIA_NM { get; set; }     
        public string CAS_NM { get; set; }     
        public string CCV_NM { get; set; }       
        public string CEC_NM { get; set; }     
        public string CEP_NM { get; set; }       
        public string CFP_NM { get; set; }
        public string CID_NM { get; set; }     
        public string CLR_NM { get; set; }
        public string CMZ_NM { get; set; }      
        public string CPO_NM { get; set; }      
        public string CPT_NM { get; set; }      
        public string CZA_NM { get; set; }   
        public string CZT_NM { get; set; }           
        public string DOX_NM { get; set; }          
        public string FLU_NM { get; set; }      
        public string GEM_NM { get; set; }       
        public string ITR_NM { get; set; }       
        public string LND_NM { get; set; }    
        public string LNZ_NM { get; set; }  
        public string MET_NM { get; set; }    
        public string MFX_NM { get; set; }      
        public string MIF_NM { get; set; }
        public string MNO_NM { get; set; }
        public string MUP_NM { get; set; }
        public string NAL_NM { get; set; }       
        public string OFX_NM { get; set; }     
        public string POS_NM { get; set; }
        public string QDA_NM { get; set; }    
        public string RIF_NM { get; set; }       
        public string STH_NM { get; set; }
        public string STR_NM { get; set; }    
        public string TCC_NM { get; set; }          
        public string TGC_NM { get; set; }
        public string TMP_NM { get; set; }      
        public string TOB_NM { get; set; }          
        public string VOR_NM { get; set; }
    }
}
