using System;
using System.Collections.Generic;
using System.Text;

namespace ALISS.Process.Batch.DTO
{
    public class IsolatesListing
    {
        public string ROW_IDX { get; set; }
        public string COUNTRY_A { get; set; }
        public string LABORATORY { get; set; }
        public string ORIGIN { get; set; }
        public string PATIENT_ID { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string SEX { get; set; }
        public string DATE_BIRTH { get; set; }
        public string AGE { get; set; }
        public string PAT_TYPE { get; set; }
        public string WARD { get; set; }
        public string INSTITUT { get; set; }
        public string DEPARTMENT { get; set; }
        public string WARD_TYPE { get; set; }
        public string SPEC_NUM { get; set; }
        public string SPEC_DATE { get; set; }
        public string SPEC_TYPE { get; set; }
        public string SPEC_CODE { get; set; }
        public string SPEC_REAS { get; set; }
        public string ISOL_NUM { get; set; }
        public string ORGANISM { get; set; }
        public string NOSOCOMIAL { get; set; }
        public string ORG_TYPE { get; set; }
        public string SEROTYPE { get; set; }
        public string BETA_LACT { get; set; }
        public string ESBL { get; set; }
        public string CARBAPENEM { get; set; }
        public string MRSA_SCRN { get; set; }
        public string INDUC_CLI { get; set; }
        public string COMMENT { get; set; }
        public string DATE_DATA { get; set; }
        public string AMK_ND30 { get; set; }
        public string AMC_ND20 { get; set; }
        public string AMP_ND10 { get; set; }
        public string SAM_ND10 { get; set; }
        public string AZM_ND15 { get; set; }
        public string CZO_ND30 { get; set; }
        public string FEP_ND30 { get; set; }
        public string CFM_ND5 { get; set; }
        public string CSL_ND30 { get; set; }
        public string CTX_ND30 { get; set; }
        public string FOX_ND30 { get; set; }
        public string CAZ_ND30 { get; set; }
        public string CZX_ND30 { get; set; }
        public string CRO_ND30 { get; set; }
        public string CXA_ND30 { get; set; }
        public string CXM_ND30 { get; set; }
        public string CHL_ND30 { get; set; }
        public string CIP_ND5 { get; set; }
        public string CLI_ND2 { get; set; }
        public string COL_ND10 { get; set; }
        public string DAP_ND30 { get; set; }
        public string DOR_ND10 { get; set; }
        public string ETP_ND10 { get; set; }
        public string ERY_ND15 { get; set; }
        public string FOS_ND200 { get; set; }
        public string FUS_ND10 { get; set; }
        public string GEN_ND10 { get; set; }
        public string GEH_ND120 { get; set; }
        public string IPM_ND10 { get; set; }
        public string LVX_ND5 { get; set; }
        public string MEM_ND10 { get; set; }
        public string NAL_ND30 { get; set; }
        public string NET_ND30 { get; set; }
        public string NIT_ND300 { get; set; }
        public string NOR_ND10 { get; set; }
        public string OFX_ND5 { get; set; }
        public string OXA_ND1 { get; set; }
        public string PEN_ND10 { get; set; }
        public string PIP_ND100 { get; set; }
        public string TZP_ND100 { get; set; }
        public string POL_ND300 { get; set; }
        public string STH_ND300 { get; set; }
        public string STR_ND10 { get; set; }
        public string TEC_ND30 { get; set; }
        public string TCY_ND30 { get; set; }
        public string SXT_ND1_2 { get; set; }
        public string VAN_ND30 { get; set; }
        public string AMX_NE { get; set; }
        public string CTX_NM { get; set; }
        public string CTX_NE { get; set; }
        public string CAZ_NM { get; set; }
        public string CAZ_NE { get; set; }
        public string CZX_NM { get; set; }
        public string CZX_NE { get; set; }
        public string CRO_NM { get; set; }
        public string CRO_NE { get; set; }
        public string CHL_NM { get; set; }
        public string CHL_NE { get; set; }
        public string CIP_NM { get; set; }
        public string CIP_NE { get; set; }
        public string CLI_NM { get; set; }
        public string CLI_NE { get; set; }
        public string COL_NM { get; set; }
        public string COL_NE { get; set; }
        public string DAP_NM { get; set; }
        public string DAP_NE { get; set; }
        public string ETP_NM { get; set; }
        public string ETP_NE { get; set; }
        public string ERY_NM { get; set; }
        public string ERY_NE { get; set; }
        public string IPM_NM { get; set; }
        public string IPM_NE { get; set; }
        public string MEM_NM { get; set; }
        public string MEM_NE { get; set; }
        public string NET_NM { get; set; }
        public string NET_NE { get; set; }
        public string PEN_NM { get; set; }
        public string PEN_NE { get; set; }
        public string VAN_NM { get; set; }
        public string VAN_NE { get; set; }
        public string AZM_NE { get; set; }
        public string SPT_ND100 { get; set; }
        public string GEN_NM { get; set; }
        public string GEN_NE { get; set; }
        public string TCY_NM { get; set; }
        public string TCY_NE { get; set; }
        public string CXM_NM { get; set; }
        public string CFM_NE { get; set; }
        public string AMP_NM { get; set; }
        public string AMP_NE { get; set; }
        public string FEP_NM { get; set; }
        public string FEP_NE { get; set; }
        public string LVX_NM { get; set; }
        public string LVX_NE { get; set; }
        public string AMK_NM { get; set; }
        public string AMK_NE { get; set; }
        public string TZP_NM { get; set; }
        public string TZP_NE { get; set; }
        public string SAM_NM { get; set; }
        public string SAM_NE { get; set; }
        public string CZO_NM { get; set; }
        public string CZO_NE { get; set; }
        public string AZM_NM { get; set; }
        public string CXM_NE { get; set; }
        public string CXA_NM { get; set; }
        public string CXA_NE { get; set; }
        public string AMC_NM { get; set; }
        public string AMC_NE { get; set; }
        public string CSL_NM { get; set; }
        public string CSL_NE { get; set; }
        public string OXA_NM { get; set; }
        public string OXA_NE { get; set; }
        public string FOX_NM { get; set; }
        public string FOX_NE { get; set; }
        public string NOR_NM { get; set; }
        public string NOR_NE { get; set; }
        public string GEH_NM { get; set; }
        public string GEH_NE { get; set; }
        public string TEC_NM { get; set; }
        public string TEC_NE { get; set; }
        public string FOS_NM { get; set; }
        public string FOS_NE { get; set; }
        public string NIT_NM { get; set; }
        public string NIT_NE { get; set; }
        public string SXT_NM { get; set; }
        public string SXT_NE { get; set; }
        public string DOR_NM { get; set; }
        public string DOR_NE { get; set; }
    }
}
